name: animate
version: '0.6.1'
category: Game
synopsis: Animation for sprites
description: Prototypical sprite animation with type-safety.
maintainer: Joe Vargas
extra-source-files:
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
default-extensions:
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- NamedFieldPuns
- ScopedTypeVariables
- OverloadedStrings
library:
  dependencies:
  - base >=4.7 && <5
  - aeson
  - bytestring
  - containers
  - text
  - vector
  - yaml
  source-dirs: library
tests:
  animate-test-suite:
    dependencies:
    - base
    - aeson
    - animate
    - containers
    - hspec
    - vector
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
github: jxv/animate
license: BSD3
