name: animate
version: '0.0.0'
category: Game
synopsis: Animation for sprites
description: Prototypical sprite animation with type-safety.
maintainer: Joe Vargas
extra-source-files:
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
default-extensions:
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- NamedFieldPuns
- ScopedTypeVariables
library:
  dependencies:
  - base
  - vector
  source-dirs: library
tests:
  animate-test-suite:
    dependencies:
    - base
    - animate
    - hspec
    - vector
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
github: jxv/animate
